"""esquema inicial

Revision ID: 18eb3573a3bc
Revises: 
Create Date: 2026-08-21 14:25:02.033097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18eb3573a3bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.String(length=40), nullable=False),
    sa.Column('operacao', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('quando', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('depois', sa.JSON(), nullable=True),
    sa.Column('motivo', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_registro_id'), ['registro_id'], unique=False)

    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=120), server_default='', nullable=False),
    sa.Column('ambito', sa.String(length=20), server_default='nacional', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feriados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feriados_data'), ['data'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('erro', sa.Text(), server_default='', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('parametros',
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('precisa_trocar_senha', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_papel'), ['papel'], unique=False)

    op.create_table('escalas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='rascunho', nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('publicada_em', sa.DateTime(), nullable=True),
    sa.Column('criada_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criada_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'versao', name='uq_escala_versao')
    )
    with op.batch_alter_table('escalas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalas_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalas_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalas_status'), ['status'], unique=False)

    op.create_table('indisponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bombeiro_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['bombeiro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indisponibilidades', schema=None) as batch_op:
        batch_op.create_index('ix_indisp_periodo', ['inicio', 'fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_indisponibilidades_bombeiro_id'), ['bombeiro_id'], unique=False)

    op.create_table('preferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bombeiro_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['bombeiro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preferencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferencias_bombeiro_id'), ['bombeiro_id'], unique=False)

    op.create_table('excecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('bombeiro_id', sa.Integer(), nullable=False),
    sa.Column('regra_dispensada', sa.String(length=10), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bombeiro_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['escala_id'], ['escalas.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excecoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excecoes_escala_id'), ['escala_id'], unique=False)

    op.create_table('explicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('escopo', sa.String(length=10), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('fatos_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('texto', sa.Text(), server_default='', nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['escala_id'], ['escalas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('explicacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explicacoes_escala_id'), ['escala_id'], unique=False)

    op.create_table('plantoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('bombeiro_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('origem', sa.String(length=10), server_default='solver', nullable=False),
    sa.Column('travado', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('observacoes', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['bombeiro_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['escala_id'], ['escalas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escala_id', 'data', name='uq_plantao_dia')
    )
    with op.batch_alter_table('plantoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plantoes_bombeiro_id'), ['bombeiro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plantoes_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_plantoes_escala_id'), ['escala_id'], unique=False)

    op.create_table('solve_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('hash_entrada', sa.String(length=64), nullable=False),
    sa.Column('entrada_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('estagios_json', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('tempo_s', sa.Float(), server_default='0', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['escala_id'], ['escalas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solve_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solve_snapshots_escala_id'), ['escala_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solve_snapshots_hash_entrada'), ['hash_entrada'], unique=False)

    op.create_table('trocas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantao_id', sa.Integer(), nullable=False),
    sa.Column('plantao_oferecido_id', sa.Integer(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('aceitante_id', sa.Integer(), nullable=True),
    sa.Column('aprovador_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='solicitada', nullable=False),
    sa.Column('motivo', sa.Text(), server_default='', nullable=False),
    sa.Column('resposta', sa.Text(), server_default='', nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolvida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aceitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['aprovador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['plantao_id'], ['plantoes.id'], ),
    sa.ForeignKeyConstraint(['plantao_oferecido_id'], ['plantoes.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trocas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trocas_aceitante_id'), ['aceitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trocas_plantao_id'), ['plantao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trocas_solicitante_id'), ['solicitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trocas_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trocas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trocas_status'))
        batch_op.drop_index(batch_op.f('ix_trocas_solicitante_id'))
        batch_op.drop_index(batch_op.f('ix_trocas_plantao_id'))
        batch_op.drop_index(batch_op.f('ix_trocas_aceitante_id'))

    op.drop_table('trocas')
    with op.batch_alter_table('solve_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solve_snapshots_hash_entrada'))
        batch_op.drop_index(batch_op.f('ix_solve_snapshots_escala_id'))

    op.drop_table('solve_snapshots')
    with op.batch_alter_table('plantoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantoes_escala_id'))
        batch_op.drop_index(batch_op.f('ix_plantoes_data'))
        batch_op.drop_index(batch_op.f('ix_plantoes_bombeiro_id'))

    op.drop_table('plantoes')
    with op.batch_alter_table('explicacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explicacoes_escala_id'))

    op.drop_table('explicacoes')
    with op.batch_alter_table('excecoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excecoes_escala_id'))

    op.drop_table('excecoes')
    with op.batch_alter_table('preferencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferencias_bombeiro_id'))

    op.drop_table('preferencias')
    with op.batch_alter_table('indisponibilidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indisponibilidades_bombeiro_id'))
        batch_op.drop_index('ix_indisp_periodo')

    op.drop_table('indisponibilidades')
    with op.batch_alter_table('escalas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalas_status'))
        batch_op.drop_index(batch_op.f('ix_escalas_mes'))
        batch_op.drop_index(batch_op.f('ix_escalas_ano'))

    op.drop_table('escalas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_papel'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('parametros')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    with op.batch_alter_table('feriados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feriados_data'))

    op.drop_table('feriados')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_registro_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_entidade'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
