"""nome curto e telefone

Revision ID: 4117d8a23438
Revises: dd227c735e22
Create Date: 2026-09-01 22:31:47.473475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4117d8a23438'
down_revision: Union[str, Sequence[str], None] = 'dd227c735e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_curto', sa.String(length=40), server_default='', nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.String(length=25), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('nome_curto')

    # ### end Alembic commands ###
