"""excecao antes da escala

Revision ID: dd227c735e22
Revises: 18eb3573a3bc
Create Date: 2026-08-21 14:26:52.399092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd227c735e22'
down_revision: Union[str, Sequence[str], None] = '18eb3573a3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excecoes', schema=None) as batch_op:
        batch_op.alter_column('escala_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_excecoes_bombeiro_id'), ['bombeiro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excecoes_data'), ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excecoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excecoes_data'))
        batch_op.drop_index(batch_op.f('ix_excecoes_bombeiro_id'))
        batch_op.alter_column('escala_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
